### ISSUE TITLE
NoSuchMethodError in labellab_mobile app

### ISSUE THREAD

**Issue by Shrawan907** [scorelab/LabelLab#301]
app build complete but when image selected from gallery it gives error  

**To Reproduce**
1. build the app (I build on android )
2. Click on 'camera icon' and take a picture
3. now come back and click on collection icon
4. select a photo 

![Screenshot_1582753071](https://user-images.githubusercontent.com/54719145/75391498-31ea2a00-5910-11ea-9c74-2f8d774179e1.png)

**Comment by cazci** [comment]
Can I know where have you hosted the server? This happens because currently, the server saves images in its instance storage only. You can bypass this error by using a local server. But if you hosted the server in a platform like Heroku, classification fails as it cannot store images in its instance.

**Comment by UdeshUK** [comment]
@Shrawan907 also, have you deployed the labellab backend and configured the mobile app according to the readme docs
